name: File Service CI

on:
  push:
    branches: [ main, develop, 'feature/**', 'bugfix/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports: [ "5432:5432" ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    - name: Download Go modules
      run: go mod download
    - name: Run linter
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
    - name: Run Unit Tests
      run: go test -v -race ./...
    - name: Run Integration Tests
      run: go test -v -race -tags=integration ./...
      env:
        DATABASE_URL_TEST: postgresql://test_user:test_password@localhost:5432/test_db?sslmode=disable
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Lumina-Enterprise-Solutions/prism-file-service
