# Nama workflow untuk proses rilis
name: Create Release and Build Binaries

# Pemicu: Hanya berjalan saat ada tag baru yang di-push dengan format v* (e.g., v1.2.3)
on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dibutuhkan untuk membuat release dan mengunggah aset

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Get Release Version from Tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Build binary for release
      run: go build -o prism-file-service-linux-amd64 .

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ env.VERSION }}
        body: "Rilis resmi versi ${{ env.VERSION }} dari Prism File Service."
        draft: false
        prerelease: false

    - name: Upload Linux Binary to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./prism-file-service-linux-amd64
        asset_name: prism-file-service-linux-amd64
        asset_content_type: application/octet-stream
